fix: add some missing includes in files
Only the bare minimum to build.
There were some clean-ups in GCC13's standard library headers and they
carry less transitive includes now, leading to missing symbols.

Fixes `error: ‘uint8_t’ was not declared in this scope` and similar.